# Generated by Django 4.2.20 on 2025-04-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('books', 'Книги'), ('clothing', 'Одежда'), ('other', 'Другое')], default='other', verbose_name='Категория')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у')], verbose_name='Состояние')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', verbose_name='Статус')),
                ('ad_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_receivers', to='ads.ad')),
                ('ad_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_senders', to='ads.ad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
