# Generated by Django 4.2.20 on 2025-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
    ]
